package it.cs.unicam.MunicipalDigitalization.util;

public enum ContentType {
    DESCRIPTION, LINK, IMAGE, VIDEO, AUDIO, FILE, LOCATION, DATE, TIME, DATETIME, NUMBER, TEXT, BOOLEAN, EMAIL, PHONE, URL, ADDRESS, PERSON, ORGANIZATION, EVENT, PRODUCT, SERVICE, OTHER
}
